-- ============================================================================
-- Migration: Add admin support and create admin account
-- ============================================================================
-- This migration adds an is_admin column to the user table and creates
-- a permanent admin account with email admin@gmail.com and password admin123
-- ============================================================================

-- Add is_admin column to user table
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN "user".is_admin IS 'Indicates if the user has admin privileges';

-- Create admin account
-- Password: admin123 (BCrypt hash will be generated by the application)
-- We'll use a BCrypt hash for 'admin123' - this is a pre-computed hash
-- Note: In production, you should generate this hash using BCryptPasswordEncoder
INSERT INTO "user" (first_name, last_name, email, password, campus_id, is_admin)
VALUES (
    'Admin',
    'User',
    'admin@gmail.com',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- BCrypt hash for 'admin123'
    1, -- Default to first campus (Harvard University)
    TRUE
)
ON CONFLICT (email) DO UPDATE SET is_admin = TRUE;

-- Create index for admin lookups
CREATE INDEX IF NOT EXISTS idx_user_is_admin ON "user"(is_admin) WHERE is_admin = TRUE;

