-- Test schema for H2 database (PostgreSQL compatibility mode)
-- This is a simplified version of the main schema for testing
-- Using H2's PostgreSQL mode with IDENTITY columns

-- Drop existing tables if they exist (in reverse dependency order)
DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS cost;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS org_leadership;
DROP TABLE IF EXISTS organization;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS campus;
DROP TABLE IF EXISTS city;

-- City table
CREATE TABLE city (
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    PRIMARY KEY (city)
);

-- Campus table
CREATE TABLE campus (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(300) NOT NULL,
    zip_code VARCHAR(20) NOT NULL,
    city VARCHAR(100) NOT NULL
);

-- User table
CREATE TABLE "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    campus_id INTEGER NOT NULL
);

-- Organization table
CREATE TABLE organization (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(2000)
);

-- Organization leadership table
CREATE TABLE org_leadership (
    user_id INTEGER NOT NULL,
    org_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, org_id)
);

-- Event table
CREATE TABLE event (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id INTEGER NOT NULL,
    campus_id INTEGER NOT NULL,
    capacity INTEGER NOT NULL,
    description VARCHAR(2000),
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL
);

-- Cost table
CREATE TABLE cost (
    type VARCHAR(50) NOT NULL,
    event_id INTEGER NOT NULL,
    cost DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (type, event_id)
);

-- Ticket table
CREATE TABLE ticket (
    user_id INTEGER NOT NULL,
    event_id INTEGER NOT NULL,
    type VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, event_id, type)
);

-- Seed data for tests
INSERT INTO city (city, country) VALUES ('Test City', 'Test Country');
INSERT INTO campus (name, address, zip_code, city) VALUES ('Test University', '123 Test St', '12345', 'Test City');
